DCMAW-9802: Create initial application infrastructure
govuk-one-login/mobile-id-check-async pull request #57
Opened 2024-08-01 17:11 UTC by sandy-may

​DCMAW-9802
### What changed
- Updated template.yaml to use KMS output and VPC output from the deployed base stacks
- Added infra tests
- Restructured repository so that only functional code is inside the src folder

### Why did it change
To test that the template can be deployed

## Checklists

- [ ] There is a ticket raised for this PR that is present in the branch name
- [ ] No PII data logged. [See guidance here](https://govukverify.atlassian.net/wiki/spaces/DCMAW/pages/3502407722/PII+Logging+Considerations)
- [ ] Demo to a BA, TA, and the team.
- [ ] Update [README](./blob/main/README.md) with any new instructions or tasks

2024-08-01 17:12 UTC, sandy-may commented on backend-api/openApiSpecs/async-public-spec.yaml
> +                      "sessionId": "37aae92b-a51e-4f68-b571-8e455fb0ec34",`
```suggestion
                      "sessionId": "37aae92b-a51e-4f68-b571-8e455fb0ec34",
```

2024-08-02 08:55 UTC, J-son1 approved these changes
Looks good!

2024-08-02 09:08 UTC, jamesamooney requested changes
Do we need to update the `dependabot.yml` with this dir change?

2024-08-02 12:29 UTC, sandy-may commented on backend-api/infra-tests/application.test.ts
> +      test("Rate and burst limit mappings are correctly", () => {
updated

2024-08-02 12:30 UTC, J-son1 approved these changes

2024-08-02 13:16 UTC, jamesamooney approved these changes

2024-08-02 13:20 UTC, merged